name: Build LuCI Theme IPK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext unzip file libssl-dev wget \
                            python3 python3-distutils python3-pip

    - name: Download OpenWRT SDK
      run: |
        wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        mv openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64 openwrt

    - name: Clone luci-theme-design-gray
      run: |
        git clone https://github.com/iFHax/luci-theme-design-gray.git

    - name: Prepare LuCI Theme Package
      run: |
        mkdir -p openwrt/package/luci-theme-design-gray
        cp -r luci-theme-design-gray/* openwrt/package/luci-theme-design-gray/

    - name: Configure SDK
      run: |
        cd openwrt
        echo "CONFIG_TARGET_x86=y" > .config
        echo "CONFIG_TARGET_x86_64=y" >> .config
        echo "CONFIG_PACKAGE_luci-theme-design-gray=y" >> .config
        make defconfig

    - name: Build luci-theme-design-gray
      run: |
        cd openwrt
        make package/luci-theme-design-gray/compile -j$(nproc) V=s

    - name: Upload built IPKs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: luci-theme-design-gray-ipks
        path: |
          openwrt/bin/packages/*/*/*.ipk
          openwrt/bin/targets/*/*/*.ipk
