name: Build OpenWRT and LuCI Theme IPK (ImmortalWRT)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential git wget curl unzip libncurses5-dev zlib1g-dev gawk gettext file \
                            libssl-dev python3.8 python3.8-distutils python3.8-venv libsqlite3-dev libtool python3-setuptools \
                            python3-pip
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
        sudo update-alternatives --set python3 /usr/bin/python3.8
        python3 --version  # Verify Python version
        python3 -m pip install --upgrade setuptools wheel  # Upgrade setuptools

    - name: Download ImmortalWRT SDK
      run: |
        wget https://downloads.immortalwrt.org/releases/21.02.1/targets/x86/64/immortalwrt-sdk-21.02.1-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        tar -xf immortalwrt-sdk-21.02.1-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        mv immortalwrt-sdk-21.02.1-x86-64_gcc-8.4.0_musl.Linux-x86_64 sdk
        cd sdk  # Ensure we're inside the SDK directory

    - name: Clone luci-theme-design-gray
      run: |
        git clone https://github.com/iFHax/luci-theme-design-gray.git

    - name: Prepare theme package
      run: |
        mkdir -p sdk/package/luci-theme-design-gray
        cp -r luci-theme-design-gray/* sdk/package/luci-theme-design-gray/

    - name: Clean SDK Environment
      run: |
        cd sdk
        make distclean  # Clean previous build environment

    - name: Configure SDK with FORCE=1
      run: |
        cd sdk
        echo "CONFIG_TARGET_x86=y" > .config
        echo "CONFIG_TARGET_x86_64=y" >> .config
        make defconfig
        # Clean and rebuild the toolchain to avoid errors
        FORCE=1 make clean
        FORCE=1 make tools/install -j$(nproc) V=s
        FORCE=1 make toolchain/install -j$(nproc) V=s

    - name: Install OpenWRT Feeds
      run: |
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Disable specific firmware packages in .config
      run: |
        cd sdk
        # Disable the firmware packages by modifying the .config file
        sed -i 's/^CONFIG_PACKAGE_eip197-mini-firmware=y/# CONFIG_PACKAGE_eip197-mini-firmware is not set/' .config
        sed -i 's/^CONFIG_PACKAGE_r8169-firmware=y/# CONFIG_PACKAGE_r8169-firmware is not set/' .config
        sed -i 's/^CONFIG_PACKAGE_e100-firmware=y/# CONFIG_PACKAGE_e100-firmware is not set/' .config

    - name: Build luci-theme-design-gray
      run: |
        cd sdk
        FORCE=1 make package/luci-theme-design-gray/compile -j$(nproc) V=s

    - name: List built IPK
      run: |
        cd sdk
        find bin/packages/ -name "*.ipk"
