name: Build LuCI Theme IPK (ImmortalWRT 2)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Python 3.8 and Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext unzip file libssl-dev wget \
                            python3.8 python3.8-distutils python3.8-venv libsqlite3-dev libtool python3-setuptools \
                            python3-pip
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
        sudo update-alternatives --set python3 /usr/bin/python3.8
        python3 --version  # Verify Python version

    - name: Install pip and Upgrade setuptools
      run: |
        sudo apt install -y python3-pip  # Install pip explicitly
        python3 -m pip install --upgrade setuptools wheel  # Upgrade setuptools

    - name: Check Python and Distutils
      run: |
        python3 -c "import distutils; print(distutils.__file__)" || echo "distutils not found"
        python3 --version
        python3 -m pip --version  # Check if pip is installed

    - name: Install Python3 distutils if not found
      run: |
        if ! python3 -c "import distutils" &> /dev/null; then
          echo "Distutils module not found, installing..."
          sudo apt-get install -y python3-distutils
        fi

    - name: Download ImmortalWRT SDK
      run: |
        wget https://downloads.immortalwrt.org/releases/21.02.1/targets/x86/64/immortalwrt-sdk-21.02.1-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        tar -xf immortalwrt-sdk-21.02.1-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        mv immortalwrt-sdk-21.02.1-x86-64_gcc-8.4.0_musl.Linux-x86_64 sdk

    - name: Clone luci-theme-design-gray
      run: |
        git clone https://github.com/iFHax/luci-theme-design-gray.git

    - name: Prepare theme package
      run: |
        mkdir -p sdk/package/luci-theme-design-gray
        cp -r luci-theme-design-gray/* sdk/package/luci-theme-design-gray/

    - name: Configure SDK with FORCE=1
      run: |
        cd sdk
        echo "CONFIG_TARGET_x86=y" > .config
        echo "CONFIG_TARGET_x86_64=y" >> .config
        make defconfig
        FORCE=1 make tools/install -j$(nproc) V=s
        FORCE=1 make toolchain/install -j$(nproc) V=s

    - name: Build luci-theme-design-gray
      run: |
        cd sdk
        FORCE=1 make package/luci-theme-design-gray/compile -j$(nproc) V=s

    - name: List built IPK
      run: find sdk/bin/packages/ -name "*.ipk"
