name: Build OpenWRT with luci-theme-design-gray

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext unzip file libssl-dev wget \
                            python3.8 python3.8-distutils python3.8-venv libsqlite3-dev libtool python3-setuptools \
                            python3-pip
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
        sudo update-alternatives --set python3 /usr/bin/python3.8

    - name: Clone OpenWRT source
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone luci-theme-design-gray
      run: |
        git clone https://github.com/iFHax/luci-theme-design-gray.git
        mkdir -p openwrt/package/luci-theme-design-gray
        cp -r luci-theme-design-gray/* openwrt/package/luci-theme-design-gray/

    - name: Configure build
      run: |
        cd openwrt
        echo "CONFIG_TARGET_x86=y" > .config
        echo "CONFIG_TARGET_x86_64=y" >> .config
        echo "CONFIG_PACKAGE_luci-theme-design-gray=y" >> .config
        make defconfig

        # Disable specific firmware
        sed -i 's/^CONFIG_PACKAGE_eip197-mini-firmware=y/# CONFIG_PACKAGE_eip197-mini-firmware is not set/' .config || true
        sed -i 's/^CONFIG_PACKAGE_r8169-firmware=y/# CONFIG_PACKAGE_r8169-firmware is not set/' .config || true
        sed -i 's/^CONFIG_PACKAGE_e100-firmware=y/# CONFIG_PACKAGE_e100-firmware is not set/' .config || true

    - name: Build luci-theme-design-gray IPK
      run: |
        cd openwrt
        make package/luci-theme-design-gray/compile V=s -j$(nproc)

    - name: Upload built IPKs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: luci-theme-design-gray-ipks
        path: |
          openwrt/bin/packages/*/*/*.ipk
          openwrt/bin/targets/*/*/*.ipk
