name: Build LuCI Theme IPK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext unzip file libssl-dev wget python3

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/22.03.6/targets/x86/64/openwrt-sdk-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-*.tar.xz
        mv openwrt-sdk-* openwrt-sdk

    - name: Prepare theme package
      run: |
        mkdir -p openwrt-sdk/package/luci-theme-design-gray
        cp -r * openwrt-sdk/package/luci-theme-design-gray/

    - name: Build the IPK
      run: |
        cd openwrt-sdk
        make defconfig
        make package/luci-theme-design-gray/compile V=s

    - name: Upload the built IPK
      uses: actions/upload-artifact@v3
      with:
        name: luci-theme-design-gray-ipk
        path: openwrt-sdk/bin/packages/*/*/luci-theme-design-gray_*.ipk
